#!/bin/bash
# install brew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

cp bashrc ~/.bashrc
cp zshrc ~/.zshrc

cp bash_profile ~/.bash_profile
cp profile ~/.profile

cp gitconfig ~/.gitconfig
cp gitignore_global ~/.gitignore_global

brew install adns
brew install autoconf
brew install automake
brew install chromedriver
brew install coreutils
brew install gdbm
brew install gettext
brew install git
brew install gmp
brew install gnupg
brew install gnutls
brew install heroku
brew install heroku-node
brew install icu4c
brew install jemalloc
brew install libassuan
brew install libevent
brew install libffi
brew install libgcrypt
brew install libgpg-error
brew install libidn2
brew install libksba
brew install libtasn1
brew install libtermkey
brew install libtool
brew install libunistring
brew install libusb
brew install libuv
brew install libvterm
brew install libyaml
brew install luajit
brew install m-cli
brew install msgpack
brew install nettle
brew install node
brew install npth
brew install openssl
brew install openssl@1.1
brew install p11-kit
brew install p7zip
brew install pcre
brew install perl
brew install pinentry
brew install pkg-config
brew install postgresql
brew install python
brew install python3
brew install readline
brew install sqlite
brew install tmux
brew install unibilium
brew install v8
brew install vim
brew install wget
brew install xz
brew install you-get
brew install zsh

cp tmux.conf ~/.tmux.conf

cd ~/
curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
tar xzf nvim-macos.tar.gz
./nvim-osx64/bin/nvim
mkdir ~/.config/nvim/
cp init.vim ~/.config/nvim/
curl -fLo ~/.nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

cd ~/
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.6.0

echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bash_profile
echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.bash_profile
echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.zshrc
echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.zshr

asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git
asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
