export ZSH=$HOME/.oh-my-zsh
export LC_ALL=en_US.UTF-8
export PATH="$PATH:$HOME/.local/bin"
export NPM_TOKEN=''
#export PATH=$HOME/bin:/usr/local/bin:$PATH

# ZSH_THEME="simple"
# ZSH_THEME="agnoster"
# ZSH_THEME="agnoster-light"
ZSH_THEME="geoffgarside"

plugins=(git fzf)
source $ZSH/oh-my-zsh.sh
if [ -f ~/.aliases ]; then
  . ~/.aliases
fi

# foxford aliases
if [ -f ~/gdrive/foxford-notes/aliases ]; then
  . ~/gdrive/foxford-notes/aliases
fi

{
  eval "$(ssh-agent -s)"
  ssh-add
} &> /dev/null

set -o vi

# masos
alias start_fanctrl='/Applications/Macs\ Fan\ Control.app/Contents/MacOS/MacsFanControl /minimized & disown'
alias stop_fanctrl='kill_batch_of_ps MacsFanControl'
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Create a new directory and enter it
function mkd() {
  mkdir -p "$@" && cd "$_";
}

# Determine size of a file or total size of a directory
function fs() {
  if du -b /dev/null > /dev/null 2>&1; then
    local arg=-sbh;
  else
    local arg=-sh;
  fi
  if [[ -n "$@" ]]; then
    du $arg -- "$@";
  else
    du $arg .[^.]* ./*;
  fi;
}

bindkey '^n' expand-or-complete
bindkey '^p' reverse-menu-complete

DISABLE_AUTO_TITLE="true"

function kill_batch_of_ps() {
  ps aux | grep $1 | echo $1
  kill -9 $(ps aux | grep $1 | grep -v 'grep' | awk '{print $2}')
}

# asdf
if [ -f ~/.asdf/asdf.sh ]; then
. ~/.asdf/asdf.sh
. ~/.asdf/completions/asdf.bash
fi

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# changing themes by cmd
alias set_light_theme="
  cp ~/.fzf.zsh.light ~/.fzf.zsh;
  cp ~/.config/nvim/init.vim.light ~/.config/nvim/init.vim;
  cp ~/.config/bat/config.light ~/.config/bat/config;
  tmux source ~/.tmux.conf.light;
  source ~/.fzf.zsh
"

alias set_dark_theme="
  cp ~/.fzf.zsh.dark ~/.fzf.zsh;
  cp ~/.config/bat/config.dark ~/.config/bat/config;
  cp ~/.config/nvim/init.vim.dark ~/.config/nvim/init.vim;
  tmux source ~/.tmux.conf.dark;
  source ~/.fzf.zsh
"

export NODE_OPTIONS="--max-old-space-size=1536"
export PATH="/usr/local/sbin:$PATH"
